In [1]:
import numpy as np

In [2]:
py_list = [1,2,3,4,5,6,7,8,9]

In [3]:
np_array = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(type(py_list))

<class 'list'>


In [5]:
print(type(np_array))

<class 'numpy.ndarray'>


In [6]:
py_multi = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np_multi = np_array.reshape(3,3)

In [8]:
print(np_multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(py_multi)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
print(np_multi.ndim)

2


In [11]:
print(np_array.ndim)

1


In [12]:
print(np_array.shape)

(9,)


In [13]:
print(np_multi.shape)

(3, 3)


In [14]:
result = np.array([1,3,5,7,9])

In [15]:
print(result)

[1 3 5 7 9]


In [16]:
res = np.arange(1,10)

# res = np.arange(1,10,)

In [17]:
print(res)

[1 2 3 4 5 6 7 8 9]
