Numpy Library

In [1]:
import numpy as np 

In [3]:
np_array=np.array([1,3,6,-3])

In [4]:
np.mean(np_array)

np.float64(1.75)

In [5]:
np.median(np_array)

np.float64(2.0)

In [7]:
np.argmin(np_array)

np.int64(3)

In [8]:
np.argmax(np_array)

np.int64(2)

In [9]:
np.std(np_array)

np.float64(3.2691742076555053)

In [10]:
print(np_array)

[ 1  3  6 -3]


In [11]:
np_array_2 = np_array
np_array[0]=-100
print(np_array_2)

[-100    3    6   -3]


In [13]:
np_array=np.array([3,6,-3])
np_array_2 =np.copy(np_array)
np_array[0]=-100
print(np_array_2)

[ 3  6 -3]
