In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import os
os.getcwd()

'/home/abdulrahman/env/Notebook/Data Mining/Python Lab - 2'

In [4]:
titanic =pd.read_excel("titanic.xlsx")

In [5]:
titanic.describe()

pclass          age        sibsp        parch         fare  \
count  1309.000000  1046.000000  1309.000000  1309.000000  1308.000000   
mean      2.294882    29.881135     0.549274     0.385027    33.295479   
std       0.837836    14.413500     2.211672     0.865560    51.758668   
min       1.000000     0.166700    -3.000000     0.000000     0.000000   
25%       2.000000    21.000000     0.000000     0.000000     7.895800   
50%       3.000000    28.000000     0.000000     0.000000    14.454200   
75%       3.000000    39.000000     1.000000     0.000000    31.275000   
max       3.000000    80.000000    71.000000     9.000000   512.329200   

          survived  
count  1309.000000  
mean      0.381971  
std       0.486055  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [6]:
titanic.head()

pclass                                             name  gender      age  \
0       1                    Allen, Miss. Elisabeth Walton  female  29.0000   
1       1                   Allison, Master. Hudson Trevor    male   0.9167   
2       1                     Allison, Miss. Helen Loraine  female   2.0000   
3       1             Allison, Mr. Hudson Joshua Creighton    male  30.0000   
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000   

   sibsp  parch  ticket      fare    cabin embarked  \
0      0      0   24160  211.3375       B5        S   
1      1      2  113781  151.5500  C22 C26        S   
2      1      2  113781  151.5500  C22 C26        S   
3      1      2  113781  151.5500  C22 C26        S   
4      1      2  113781  151.5500  C22 C26        S   

                         home.dest  survived  
0                     St Louis, MO         1  
1  Montreal, PQ / Chesterville, ON         1  
2  Montreal, PQ / Chesterville, ON         0  
3  Montreal, PQ / Chesterville, ON         0  
4  Montreal, PQ / Chesterville, ON         0

In [15]:
bilet_sinifi=titanic['pclass'].value_counts()

In [17]:
toplam_yolucu = len(titanic)

In [18]:
bos_sayisi = titanic['pclass'].isnull().sum()

In [22]:
bos_sayisi = 0
for i in range(toplam_yolucu):
    if pd.isnull(titanic['pclass'].iloc[i]):  
        bos_sayisi += 1

bos_sayisi  

0

In [23]:
t=0
for i in range(toplam_yolucu):
    if titanic['pclass'][i]==3 and titanic['survived'][i]==1:
        t+=1

In [47]:
t=0
for i in range(toplam_yolucu):
    if titanic['gender'][i]=='female' and titanic['survived'][i]==1:
        t+=1

In [39]:
t=0
for i in range(toplam_yolucu):
    if titanic['gender'][i]=='male' and titanic['survived'][i]==1:
        t+=1

In [40]:
print(f'ucuncu sinifi yolcularin % {np.ceil(t/709*100)}\'u yasmisitir')

ucuncu sinifi yolcularin % 23.0'u yasmisitir


In [48]:
toplam_kadin_sayisi=len(np.where(titanic['gender']=='female')[0])

In [44]:
toplam_kadin_sayisi=len(np.where(titanic['gender']=='male')[0])

In [49]:
print(f'kadinlerin sinifi yolcularin % {np.ceil(t/466*100)}\'u yasmisitir')

kadinlerin sinifi yolcularin % 73.0'u yasmisitir


In [51]:
print(f'erkekin sinifi yolcularin % {np.ceil(t/843*100)}\'u yasmisitir')

erkekin sinifi yolcularin % 41.0'u yasmisitir


In [61]:
toplam_yolcu_sayisi = len(titanic)
cinsiyet = np.zeros(toplam_yolcu_sayisi)
cinsiyet[np.where(titanic['gender'] == 'male')[0]] = 1
cinsiyet 

array([0., 1., 0., ..., 1., 1., 1.])

In [65]:
ort_yas = titanic['age'].mean()

yas = np.zeros(toplam_yolcu_sayisi)

for i in range(toplam_yolcu_sayisi):
    if np.isnan(titanic['age'].iloc[i]) or titanic['age'].iloc[i] < 1 or titanic['age'].iloc[i] > 100:
        yas[i] = ort_yas
    else:
        yas[i] = titanic['age'].iloc[i]

yas


array([29.        , 29.88113451,  2.        , ..., 26.5       ,
       27.        , 29.        ])

In [66]:
yas=np.reshape(yas,(toplam_yolcu_sayisi,1))

In [67]:
makul_kardes_sayisi=[]
for i in range(toplam_yolcu_sayisi):
        if titanic['sibsp'][i]>0 and titanic['sibsp'][i]<8:
            makul_kardes_sayisi.append(titanic['sibsp'][i])

In [68]:
kardes=np.zeros(toplam_yolcu_sayisi)
for i in range(toplam_yolcu_sayisi):
    if np.isnan(titanic['sibsp'].iloc[i]) or titanic['sibsp'].iloc[i] >=0 or titanic['sibsp'].iloc[i] < 8:
        kardes[i] = ort_yas
    else:
        kardes[i] = titanic['sibsp'].iloc[i]

kardes

array([29.88113451, 29.88113451, 29.88113451, ..., 29.88113451,
       29.88113451, 29.88113451])

In [69]:
ucretler=[]
for i in range(toplam_yolcu_sayisi):
    if not np.isnan(titanic['fare'][i]):
        ucretler.append(titanic['fare'][i])

In [70]:
max_makul_ucret=np.mean(ucretler)+3*np.std(ucretler)

In [73]:
max_makul_ucret

np.float64(188.51211637875963)

In [75]:
ucret = np.zeros(toplam_yolcu_sayisi)
for i in range(toplam_yolcu_sayisi):
    if np.isnan(data['fare'].iloc[i]) or data['fare'].iloc[i] > max_makul_ucret:
        ucret[i] = data['fare'].mean()  
    else:
        ucret[i] = data['fare'].iloc[i]

ucret

NameError: name 'data' is not defined